baseURL = "https://totally.sh/"
locale = "en-us"
title = "Totally"
disableKinds = ["taxonomy"]

[params]
  description = "A local CLI for understanding agent sessions."

[menus]
  [[menus.main]]
    name = "install"
    pageRef = "/install"
    weight = 5
  [[menus.main]]
    name = "docs"
    pageRef = "/docs"
    weight = 10
  [[menus.main]]
    name = "community"
    url = "#"
    weight = 20
  [[menus.main]]
    name = "GitHub"
    url = "https://github.com/rybkr/totally"
    weight = 30
